root: true

extends:
  - eslint:recommended
  - prettier

ignorePatterns:
  - dist

overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - '@typescript-eslint'

  - files: ['*.js', '*.cjs', '*.mjs']
    excludedFiles: ['src/**/*', 'test/**/*']
    env:
      node: true
      es2021: true
    parserOptions:
      ecmaVersion: latest

  - files: ['*.js', '*.mjs']
    parserOptions:
      sourceType: module

  - files: ['scripts/**/*']
    env:
      node: true
      es2021: true
    parserOptions:
      ecmaVersion: latest
